const screens=["Executive Pulse","Portfolio Health","Financial Command","Resource Capacity","Delivery Control","Risk Radar","Dependency Mesh","AI PMO Copilot","Agent Control Center","Program Digital Twin","Scenario Simulator","Executive Storytelling","Settings & Governance"];
const data={kpis:[['Portfolio Value','$248M','+12.4%','up'],['Delivery Confidence','91%','+6.8%','up'],['Risk Exposure','$7.2M','-18.1%','up'],['Capacity Load','84%','-3.5%','down']],programs:['Apollo ERP','Nova CX','Atlas Cloud','Helios Data','Orion Security','Zenith AI'],months:['Jan','Feb','Mar','Apr','May','Jun'],spend:[18,22,26,31,29,35],health:[92,86,78,94,73,88],risks:['Vendor latency predicted in Atlas Cloud','Security test gate trending amber','Finance change saturation exceeds threshold','Data migration defect cluster stabilizing'],agents:['RAID Synthesizer','Status Narrator','Dependency Negotiator','Capacity Forecaster','Executive Briefing Agent','Quality Sentinel']};
const nav=document.getElementById('nav'),title=document.getElementById('screen-title'),screen=document.getElementById('screen'),kpis=document.getElementById('kpis');let active=0,slide=0;
function el(tag,cls,html=''){const n=document.createElement(tag);if(cls)n.className=cls;n.innerHTML=html;return n}
function initNav(){screens.forEach((s,i)=>{const b=el('button','',`${String(i+1).padStart(2,'0')} · ${s}`);b.onclick=()=>render(i);nav.appendChild(b)})}
function renderKpis(){kpis.innerHTML='';data.kpis.forEach(([l,v,t,d],i)=>{const c=el('article','kpi',`<small>${l}</small><strong data-target="${v.replace(/[^0-9.]/g,'')}">0</strong><span class="trend ${d}">${t} vs plan</span>`);kpis.appendChild(c);animateValue(c.querySelector('strong'),v,i*120)})}
function animateValue(node,formatted,delay){setTimeout(()=>{let raw=parseFloat(node.dataset.target),pre=formatted[0]=='$'?'$':'',post=formatted.includes('%')?'%':formatted.includes('M')?'M':'';let n=0,step=raw/36;const id=setInterval(()=>{n+=step;if(n>=raw){n=raw;clearInterval(id)}node.textContent=pre+(raw<20?n.toFixed(1):Math.round(n))+post},22)},delay)}
function render(i=0){active=i;[...nav.children].forEach((b,x)=>b.classList.toggle('active',x===i));title.textContent=screens[i];renderKpis();screen.innerHTML='';builders[i]();}
const card=(span,h,body)=>screen.appendChild(el('article',`card span-${span}`,`<small>${h}</small>${body}`));
function svgLine(vals,color='var(--cyan)'){let pts=vals.map((v,i)=>`${40+i*100},${230-v*2}`).join(' ');return `<svg class="chart" viewBox="0 0 600 260"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#3de8ff"/><stop offset="1" stop-color="#ff4fd8"/></linearGradient></defs><polyline points="${pts}" fill="none" stroke="url(#g)" stroke-width="8" stroke-linecap="round"/><path d="M${pts.replaceAll(' ',',')} L540 250 L40 250Z" fill="rgba(61,232,255,.08)"/>${vals.map((v,i)=>`<circle cx="${40+i*100}" cy="${230-v*2}" r="7" fill="${color}"/>`).join('')}</svg>`}
function bars(vals){return vals.map((v,i)=>`<div class="metric-row"><span>${data.programs[i]}</span><b>${v}%</b></div><div class="bar"><i style="width:${v}%"></i></div>`).join('')}
function copilot(){return `<div id="ai-output"><h3>Generated PMO Brief</h3><p>${data.risks[0]}. Recommend resequencing integration testing, adding two cloud engineers, and escalating procurement decision rights for 10 business days.</p></div><button class="primary-btn" onclick="generateBrief()">Regenerate AI Output</button>`}
window.generateBrief=()=>{const options=['Portfolio remains fundable if Q3 scope is protected and resource contention is reduced by 9%.','AI recommends a go-forward decision with gated remediation for Orion Security and Atlas Cloud.','Executive narrative: confidence is improving, but dependency age requires direct sponsor action.'];document.getElementById('ai-output').innerHTML=`<h3>Generated PMO Brief</h3><p>${options[Math.floor(Math.random()*options.length)]}</p>`}
const builders=[()=>{card(8,'Portfolio trajectory',svgLine(data.health));card(4,'Operating signals',bars([91,84,76,88]));card(6,'Decision queue','<p>3 sponsor decisions unblock $41M in value. AI confidence: 98%.</p><span class="pill">Approve Atlas vendor bridge</span><span class="pill">Shift 6 FTE to Helios</span>');card(6,'Risk heat',data.risks.map(r=>`<div class="log-item">${r}</div>`).join(''))},()=>{card(7,'Program health index',svgLine(data.health));card(5,'Program scorecards',bars(data.health));card(12,'Portfolio swimlanes',data.programs.map(p=>`<span class="pill">${p} · ${70+Math.round(Math.random()*25)}% ready</span>`).join(''))},()=>{card(8,'Run-rate spend',svgLine(data.spend,'var(--amber)'));card(4,'Financial controls',bars([94,82,71,89]));card(12,'Budget narrative','<p>$248M portfolio value, $35M June spend, $7.2M exposure. Forecast variance remains inside governance tolerance.</p>')},()=>{card(6,'Capacity by role',bars([96,88,79,67,91,74]));card(6,'AI allocation recommendation','<p>Move 2 architects from Nova CX to Atlas Cloud and backfill QA with managed service burst capacity.</p>');card(12,'Team sentiment','<span class="pill">Burnout risk: medium</span><span class="pill">Critical skills: cloud, data, cyber</span>')},()=>{card(8,'Milestone burnup',svgLine([40,52,61,69,80,91]));card(4,'Delivery gates',bars([100,94,88,77]));card(12,'Control room feed',data.programs.map(p=>`<div class="log-item">${p}: next milestone forecast recalculated by delivery control engine.</div>`).join(''))},()=>{card(5,'Top predictive risks',data.risks.map(r=>`<div class="log-item">⚠ ${r}</div>`).join(''));card(7,'Exposure trend',svgLine([42,38,34,31,25,22],'var(--red)'));card(12,'Mitigation automation','<button class="primary-btn" onclick="alert(\'Mitigation plan generated locally.\')">Generate mitigation plan</button>')},()=>{card(12,'Dependency mesh','<div class="node-map" id="mesh"></div>');setTimeout(drawNodes,0)},()=>card(12,'AI PMO Copilot',copilot()),()=>{card(5,'Agent roster',data.agents.map(a=>`<span class="pill">${a}</span>`).join(''));card(7,'Live agent activity',`<div class="agent-log" id="agent-log"></div>`);startAgentLog()},()=>{card(12,'Program Digital Twin','<div class="node-map" id="mesh"></div><p>Click nodes to inspect simulated value flow, risk propagation, and delivery confidence.</p>');setTimeout(drawNodes,0)},()=>{card(6,'Scenario controls','<button class="primary-btn" onclick="simulate()">Run what-if simulation</button><div id="sim"></div>');card(6,'Simulation chart',svgLine([65,69,73,78,83,89]))},()=>openStory(),()=>{card(6,'Governance model','<p>Offline-first static shell. No external APIs, no backend, no build step, no telemetry.</p>');card(6,'Controls','<span class="pill">Role-aware navigation</span><span class="pill">Audit-ready AI logs</span><span class="pill">Enterprise dark mode</span>')}];
function drawNodes(){const m=document.getElementById('mesh');if(!m)return;data.programs.forEach((p,i)=>{const n=el('div','node',p.split(' ')[0]);n.style.cssText=`width:${78+i*5}px;height:${78+i*5}px;left:${8+(i%3)*30}%;top:${20+Math.floor(i/3)*38}%`;n.onclick=()=>alert(`${p}: confidence ${data.health[i]}%, dependency impact ${i+2} systems`);m.appendChild(n)})}
function startAgentLog(){const log=document.getElementById('agent-log');let x=0;const add=()=>{if(!log)return;log.prepend(el('div','log-item',`${new Date().toLocaleTimeString()} · ${data.agents[x++%data.agents.length]} completed autonomous analysis.`));if(log.children.length>12)log.lastChild.remove()};add();clearInterval(window.agentTimer);window.agentTimer=setInterval(add,1800)}
window.simulate=()=>document.getElementById('sim').innerHTML=`<div class="log-item">Scenario complete: +${Math.round(Math.random()*8+4)}% confidence, -$${(Math.random()*2+1).toFixed(1)}M exposure, ${Math.round(Math.random()*4+2)} weeks protected.</div>`;
const story=[['The portfolio is accelerating','AI signals show improving confidence across six strategic programs while preserving fiscal guardrails.'],['Three decisions unlock value','Sponsor action on vendors, capacity, and scope protection unlocks $41M in near-term value.'],['Autonomous PMO is online','Agents continuously synthesize RAID, dependencies, capacity, and executive-ready narratives.']];
function openStory(){document.getElementById('story-overlay').classList.add('open');showSlide()}
function showSlide(){document.getElementById('story-title').textContent=story[slide][0];document.getElementById('story-copy').textContent=story[slide][1];document.getElementById('story-visual').innerHTML=svgLine(data.health.slice(0,6).map(v=>v-slide*4));document.getElementById('slide-count').textContent=`${slide+1} / ${story.length}`}
document.getElementById('story-mode-btn').onclick=openStory;document.getElementById('story-close').onclick=()=>document.getElementById('story-overlay').classList.remove('open');document.getElementById('next-slide').onclick=()=>{slide=(slide+1)%story.length;showSlide()};document.getElementById('prev-slide').onclick=()=>{slide=(slide+story.length-1)%story.length;showSlide()};document.getElementById('copilot-spark').onclick=()=>render(7);
function particles(){const c=document.getElementById('particle-field'),ctx=c.getContext('2d');let ps=[];function size(){c.width=innerWidth;c.height=innerHeight;ps=Array.from({length:90},()=>({x:Math.random()*c.width,y:Math.random()*c.height,v:Math.random()*1+.2,r:Math.random()*2+1}))}function tick(){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='rgba(61,232,255,.55)';ps.forEach(p=>{p.y-=p.v;if(p.y<0)p.y=c.height;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()});requestAnimationFrame(tick)}addEventListener('resize',size);size();tick()}initNav();render();particles();
